services:
    cm-analyzer:
        container_name: cm-analyzer
        image: cm-analyzer-test:playback-xcm

        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /media/tv_record:/recorded:ro
            - ./epgstation/cm-analyzer-data:/data
            - ./epgstation/cm-analyzer-data/logos:/tmp/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/logo
            - ./epgstation/cm-analyzer-test/ChList.csv:/tmp/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/setting/ChList.csv:ro

        environment:
            TZ: "Asia/Tokyo"
            RECORDED_ROOT: "/recorded"
            DATA_ROOT: "/data"

        restart: always

        networks:
            - epgstation-network

networks:
    epgstation-network:
        external: true
        name: docker-mirakurun-epgstation_default
